# Installs and builds the package (including native modules)
# Using the image: balenalib/raspberrypi4-64-alpine-node:16
name: Docker Install & Build - Raspberry Pi 4

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build for Raspberry Pi 4
      run: docker build --platform=linux/arm64/v8 --file Dockerfile --tag raspberry-pi-4:$(date +%s) .
